name: provisioning EKS using terraform and automated by github Actions
on:
  push:
    branches: [main]
jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY: ${{ $secrets.AWS_SECRET_KEY }}
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: 1.7.5
    - name: terraform init
      run: terraform init
    - name: terraform format check
      run: terraform fmt -check
    - name: terraform plan
      run: terraform plan
 #  - name: terraform apply
  #   run: terraform apply -auto-approve
      
      
    
     
    

